openapi: "3.0.0"
info:
  title: "my api"
  version: "1.0.1"
  description: "some random api"
  contact:
    name: "me"
    email: "yuri.khomyakov@ironsrc.com"
    url: "asddsasad"
  license:
    name: "dasdsaa"
    url: "dsadsa"
servers:
  - url: "sadadsadads"
    description: "asdadsdssdaasd"
paths:
  /api/test/{param}:
    get:
      tags:
        - "main route"
        - "simple tag"
      description: "returns whatever it receives"
      summary: "simple summary for swagger"
      parameters:
        - name: "param"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apitestparam-200-get"
        400:
          description: "400"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apitestparam-400-get"
  /api/{status}:
    post:
      tags:
        - "oven"
        - "jenkins"
      description: "returns whatever it receives"
      summary: "simple summary for swagger"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apistatus-body-post"
      parameters:
        - name: "status"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apistatus-200-post"
        400:
          description: "400"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apistatus-400-post"
components:
  schemas:
    apitestparam-200-get:
      type: "object"
      properties:
        inner:
          type: "object"
          properties:
            name:
              type: "string"
            field1:
              type: "number"
            field2:
              type: "object"
              properties:
                param:
                  type: "string"
            array:
              type: "string"
              enum:
                - "1"
                - "other"
                - "last"
            any:
              type: "array"
              items:
                type: "boolean"
            dict:
              type: "object"
            list:
              type: "array"
              items:
                type: "string"
        lala:
          type: "number"
    apitestparam-400-get:
      type: "string"
    apistatus-body-post:
      type: "string"
    apistatus-200-post:
      type: "object"
      properties:
        inner:
          type: "object"
          properties:
            name:
              type: "string"
            field1:
              type: "number"
            field2:
              type: "object"
              properties:
                param:
                  type: "string"
            array:
              type: "string"
              enum:
                - "1"
                - "other"
                - "last"
            any:
              type: "array"
              items:
                type: "boolean"
            dict:
              type: "object"
            list:
              type: "array"
              items:
                type: "string"
        lala:
          type: "number"
    apistatus-400-post:
      type: "string"
