openapi: "3.0.0"
info:
  title: "my api"
  version: "1.0.1"
  description: "some random api"
  contact:
    name: "me"
    email: "yuri.khomyakov@ironsrc.com"
    url: "asddsasad"
  license:
    name: "MIT"
    url: "dsadsa"
servers:
  - url: "sadadsadads"
    description: "asdadsdssdaasd"
paths:
  /api/example/path:
    get:
      tags:
        - "some tag"
        - "some other tag"
      description: "example route"
      summary: "summary for swagger"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/apiexamplepath-body-get"
      responses:
        200:
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/apiexamplepath-200-get"
components:
  schemas:
    apiexamplepath-body-get:
      type: "string"
    apiexamplepath-200-get:
      type: "array"
      items:
        type: "object"
